### ISSUE TITLE
Full screen crashes on alt-tab on some - not all - computers.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/CommunityKitPublic#332]
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Microsoft.Xna.Framework.Graphics.OpenGLDevice.SwapBuffers(System.Nullable`1&lt;Microsoft.Xna.Framework.Rectangle&gt;, System.Nullable`1&lt;Microsoft.Xna.Framework.Rectangle&gt;, IntPtr)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present()
   at Microsoft.Xna.Framework.Game.EndDraw()
   at Microsoft.Xna.Framework.Game.RedrawWindow()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.Win32OnPaint(IntPtr, IntPtr)

**Comment by ZaneDubya** [comment]
Believe this is fixed

**Comment by ZaneDubya** [comment]
Believe this is fixed (again)
