### ISSUE TITLE
Crash on event in TwMap10.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/CommunityKitPublic#617]
Error: Packet event error. Disconnecting net state.
Exception: Bad GetState 0x00 0x04
Stack trace:    at XPT.Games.Twinion.Entities.TwPlayerMapData.GetFlag(Int32 flagType, Int32 flagIndex) in Z:\Documents\GitHub\CommunityKit\CommunityServer\Games\Twinion\Entities\TwPlayerMapData.cs:line 103  
   at XPT.Games.Twinion.Maps.TwMap10.FnEvent1C(TwPlayerServer player, MapEventType type, Boolean doMsgs) in Z:\Documents\GitHub\CommunityKit\CommunityServer\Games\Twinion\Maps\TwMap10.cs:line 231
   at XPT.Games.Twinion.Maps.TwMap.InternalMapEventHandler(MapEventHandler eventHandler, TwPlayerServer player, MapEventType type, Boolean doMsgs) in Z:\Documents\GitHub\CommunityKit\CommunityServer\Games\Twinion\Maps\TwMap.cs:line 897
   at XPT.Games.Generic.Entities.GenericPlayer.MoveEventHandler(Func`3 funcEventHandler, GenericPlayer player, MapEventType type) in Z:\Documents\GitHub\CommunityKit\CommunityServer\Games\Generic\Entities\GenericPlayer_Movement.cs:line 298
   at XPT.Games.Generic.Entities.GenericPlayer.MoveToMap(AMap map, MapPoint newPosition, Boolean suppressRandomEncounters, Boolean suppressScriptedEncounters) in Z:\Documents\GitHub\CommunityKit\CommunityServer\Games\Generic\Entities\GenericPlayer_Movement.cs:line 233
   at XPT.Games.Generic.Maps.AMap.EventSink_DungeonMoveRequest(GenericPlayer m, Direction direction) in Z:\Documents\GitHub\CommunityKit\CommunityServer\Games\Generic\Maps\AMap.cs:line 48
   at XPT.Core.Network.MessagePump.HandleReceive(NetState ns) in Z:\Documents\GitHub\CommunityKit\CommunityServer\Core\Network\MessagePump.cs:line 154

**Comment by ZaneDubya** [comment]
Twinion has 8 room state flags, where Yserbius only had 4.

**Comment by ZaneDubya** [comment]
Fixed
