### ISSUE TITLE
The system cannot find the file specified issue after update

### ISSUE THREAD

**Issue by angry-dad** [ZaneDubya/CommunityKitPublic#971]
I am enjoying playing the game, great job. 

I ran into an issue after updating today (11/20/2021) and see the following trace exception log after trying to run the client. The game opens briefly and then immediately exits. I tried deleting all user AppData and reinstalling without success:

The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at XPT.Legacy.Games.Loading.LoadingSupport.BuildLPKResourcesAndDeployLocally(String pathInput, String pathOutput) in Z:\Documents\GitHub\KitCommunity\CommunityClient\Legacy\Games\Loading\LoadingSupport.cs:line 30
   at XPT.Tactics.Modes.TacticsModeInitialize.OnInitialize() in Z:\Documents\GitHub\KitCommunity\CommunityClient\Tactics\Modes\TacticsModeInitialize.cs:line 14
   at XPT.Core.Modes.ModeManager.set_Current(AMode value) in Z:\Documents\GitHub\KitCommon\XptDesktop\Core\Modes\ModeManager.cs:line 31
   at XPT.Core.CoreKernel.Update(GameTime gameTime) in Z:\Documents\GitHub\KitCommon\XptDesktop\Core\CoreKernel.cs:line 85
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at XPT.Core.EntryPoint.Main(String[] args) in Z:\Documents\GitHub\KitCommon\XptDesktop\Core\EntryPoint.cs:line 16

**Comment by ZaneDubya** [comment]
Whoops! An update on my end left the game unable to load.

A fix is in now and your work in the dungeon may resume :)

Thank you for the report!!!

**Comment by angry-dad** [comment]
Thanks, confirmed working again here. Appreciate it.
