### ISSUE TITLE
Data or Target is null during combat, causes fatal crash.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/CommunityKitPublic#988]
Error:
System.NullReferenceException: Object reference not set to an instance of an object.
   at XPT.Legacy.Systems.Battle.Yserbius.YsEncounter.Phase2_PlayerAction_SpellOrSkill_Underlying(SmsgBattleRound roundPacket, GenericPlayer source, ISkillData data, Int32 levelZeroIndexed, Boolean isSpell, ETypeOfTarget targetType, Boolean doSound, Boolean& useMana) in Z:\Documents\GitHub\KitCommunity\CommunityServer\Legacy\Systems\Battle\Yserbius\YsEncounter.cs:line 534
   at XPT.Legacy.Systems.Battle.Yserbius.YsEncounter.Phase2_PlayerAction_SpellOrSkill(SmsgBattleRound roundPacket, GenericPlayer attacker, Int32 skillIndex, Boolean isSpell) in Z:\Documents\GitHub\KitCommunity\CommunityServer\Legacy\Systems\Battle\Yserbius\YsEncounter.cs:line 493
   at XPT.Legacy.Systems.Battle.GenericEncounter.Phase2_Begin_CreateRoundPacketAndSend() in Z:\Documents\GitHub\KitCommunity\CommunityServer\Legacy\Systems\Battle\GenericEncounter.cs:line 547
   at XPT.Legacy.Systems.Battle.GenericEncounter.OnTimerTick() in Z:\Documents\GitHub\KitCommunity\CommunityServer\Legacy\Systems\Battle\GenericEncounter.cs:line 320
   at XPT.Timer.Slice() in Z:\Documents\GitHub\KitCommunity\CommunityServer\Timer.cs:line 302
   at XPT.Kernel.Run(String[] args) in Z:\Documents\GitHub\KitCommunity\CommunityServer\Kernel.cs:line 305
This exception is fatal.
Exiting...done.

**Comment by ZaneDubya** [comment]
Fixed
